### ISSUE TITLE
Add SystemSKU

### ISSUE THREAD

**Issue by dhatch48** [jonconwayuk/PowerShell_Gather#15]
For Panasonic toughbooks I require getting the system SKU to match driver packages.
`$TSvars.Add('SystemSKU', $ComputerSystem.SystemSKUNumber)`

**Comment by jonconwayuk** [comment]
Due to me being fairly inexperienced/useless with GitHub I'll add your change myself so I don't make an arse of it. I'll get it added as soon as I can :)
