### ISSUE TITLE
Get-NetworkInfo problem

### ISSUE THREAD

**Issue by jpfieber** [jonconwayuk/PowerShell_Gather#7]
I got an error on the Get-NetworkInfo function. IsOnEthernet was returning True twice, probably related to running Hyper-V?  I did the following, which I think still accomplishes the desired result:
```
function Get-NetworkInfo {

    (Get-CimInstance -ClassName 'Win32_NetworkAdapterConfiguration' -Filter 'IPEnabled = 1') | ForEach-Object {

        $_.IPAddress | ForEach-Object {
            if ($_ -ne $null) {
                if ($_.IndexOf('.') -gt 0 -and !$_.StartsWith('169.254') -and $_ -ne '0.0.0.0') {

                    if ($TSvars.ContainsKey('IPAddress')) {
                        $TSvars['IPAddress'] = $TSvars['IPAddress'] + ',' + $_
                    }
                    else {
                        $TSvars.Add('IPAddress', $_)
                    }
                }
            }
        }

        $_.DefaultIPGateway -split ',' | Select-Object -First '1' | ForEach-Object {
            if ($_ -ne $null -and $_.IndexOf('.') -gt 0) {

                if ($TSvars.ContainsKey('DefaultGateway')) {
                    $TSvars['DefaultGateway'] = $TSvars['DefaultGateway'] + ',' + $_
                }
                else {
                    $TSvars.Add("DefaultGateway", $_)
                }
            }
        }

        $EthernetConnection = Get-CimInstance -ClassName 'Win32_NetworkAdapter' | Where-Object { $_.Name -like "*Ethernet Connection*" -or $_.Name -like "*Realtek PCIe*" -and $_.NetConnectionStatus -eq '2' }

        if ($null -eq $EthernetConnection) {
            $IsOnEthernet = $false
        }
        else {
            $IsOnEthernet = $true
        }
    }
    
    if($IsOnEthernet -contains "True") {
        $TSvars.Add('IsOnEthernet', "True")
    } else {
        $TSvars.Add('IsOnEthernet', "False")
    }

    $Nic = (Get-CimInstance -ClassName 'Win32_NetworkAdapter' -Filter 'NetConnectionStatus = 2')

    $TSvars.Add('MacAddress', $Nic.MACAddress -join ',')

}
```

**Comment by jonconwayuk** [comment]
Hi - I've done most of my testing on Hyper-V VMs so I don't think it will be that. I wonder if you have more than one connected NIC attached to the VM?

**Comment by jpfieber** [comment]
Actually I'm not running within a VM, the computer is hosting VMs. So an IPconfig shows two Hyper-V Virtual Ethernet Adapters (looks like I setup an additional 'Virtual Switch' in addition to the 'Default Switch').

**Comment by jonconwayuk** [comment]
Magic. I figured it would be to do with multiple NIC's as that's one of the scenarios I haven't tested it on! I've just added a 2nd Virtual Switch to my host and I can reproduce the error you're getting. Let me do some quick tests and I'll update with a new release once I sort it. Thanks for your input! :-)

**Comment by jonconwayuk** [comment]
Bug Fix: Updates to 'Get-NetworkInfo' function to prevent '$IsOnEthernet' failing on devices with multiple NICs/Virtual Switches. 

Fix included in v1.2 - let me know if it's sorted for you jpfeiber and I'll close this issue down.

**Comment by jpfieber** [comment]
That ran clean on the same computer. Thanks for the quick fix!

**Comment by jonconwayuk** [comment]
You're welcome. I'm keen for the script to be used by people so I'm happy to fix things sharpish :-) Let me know if you have any more feedback. For new ideas probably best to comment on my blog post: https://jonconwayuk.wordpress.com/2020/04/23/powershell-gather-moving-away-from-mdt-integrated-task-sequences-in-microsoft-endpoint-configuration-manager-mecm/ Cheers, JC
